Feature/iotsdk 226 json decoupling
pywtk/iotc-yocto-c-sdk pull request #1
Opened 2023-10-04 14:16 UTC by vputys

2023-10-05 10:39 UTC, pywtk requested changes
comments regard CMake changes & deleted files`

2023-10-05 10:39 UTC, pywtk commented on .gitignore
Any reason for this change?

2023-10-05 10:39 UTC, pywtk commented on meta-myExampleIotconnectLayer/recipes-apps/telemetry-demo/files/cmke-src/CMakeLists.txt
I see that the file structure is this:
cmke-src/
├── CMakeLists.txt
├── components
│   └── json_parser
│       ├── CMakeLists.txt
│       ├── inc
│       │   └── json_parser.h
│       └── json_parser.c
├── config
│   └── app_config.h
└── main.c

& the CMakeLists.txt files support this.

It seems to me the same resutls can be achieved with a structure like this:
cmke-src/
├── CMakeLists.txt
├── config
│   └── app_config.h
├── json_parser.c
├── json_parser.h
└── main.c

& a single change to the one CMakeLists.txt file:

--- a/meta-myExampleIotconnectLayer/recipes-apps/telemetry-demo/files/cmke-src/CMakeLists.txt
+++ b/meta-myExampleIotconnectLayer/recipes-apps/telemetry-demo/files/cmke-src/CMakeLists.txt
@@ -11,5 +11,5 @@ include(GNUInstallDirs)
 
 include_directories(config PRIVATE ${IOTC_C_LIB_INCLUDE_DIR} ${IOTC_C_SDK_INCLUDE_DIR})
 add_executable(telemetry-demo main.c)
-
+target_sources(telemetry-demo PUBLIC json_parser.c)
 target_link_libraries(telemetry-demo iotc-c-generic-sdk)

I'm worried I'm missing something important about the proposed approach, wee chat to discuss?

2023-10-05 10:39 UTC, pywtk commented on meta-myExampleIotconnectLayer/recipes-apps/telemetry-demo/files/cmke-src/components/json_parser/CMakeLists.txt
Comment above exploring the requirement for multiple CMakeList.txt files

2023-10-05 10:39 UTC, pywtk commented on meta-myExampleIotconnectLayer/recipes-apps/telemetry-demo/files/eg-private-repo-data/.gitignore
Comment above re more gitignores?

2023-10-05 10:39 UTC, pywtk commented on meta-myExampleIotconnectLayer/recipes-apps/telemetry-demo/files/eg-private-repo-data/config-symmtrcKy.json
why delete these files?

2023-10-05 10:39 UTC, pywtk commented on meta-myExampleIotconnectLayer/recipes-apps/telemetry-demo/telemetry-demo_0.1.bb
Comment above re extra CMake changes & presumably the implied required change to the recipe here

2023-10-05 10:42 UTC, vputys commented on .gitignore
if I understood you right - you wanted eg-private-repo-data folder's contents to not appear on git?
I noticed that it wasn't the case and changed .gitignores then (includes the folder, but not the contents)

2023-10-06 08:16 UTC, pywtk approved these changes

2023-10-09 14:33 UTC, pywtk approved these changes
looks ok

2023-10-09 14:33 UTC, merged